### ISSUE TITLE
When i enter in 'asdakuhdkajsdn' it breaks

### ISSUE THREAD

**Issue by ketanketanketan** [rshnn/RxLethality#1]
Here's the Terminal output: 

```
$ node app
listening
nyquil
benadryl
asdakuhdkajsdn
/Users/ketpatel/code/RxLethality/app.js:31
    var searchlength    = json.meta.results.total;
                                   ^
TypeError: Cannot read property 'results' of undefined
    at Request._callback (/Users/ketpatel/code/RxLethality/app.js:31:36)
    at Request.self.callback (/Users/ketpatel/code/RxLethality/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/ketpatel/code/RxLethality/node_modules/request/request.js:1063:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/ketpatel/code/RxLethality/node_modules/request/request.js:1009:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by rshnn** [comment]
An NULL-check after the search is instigated would probably fix this.  Thanks for trying to blow up the app.  I didn't give myself enough time to do so
